### PR TITLE
Laws for mutable unboxed vectors

### PR DESCRIPTION
**Pull request by Bodigrim**
This is a port of [`Test.QuickCheck.Classes.muvectorLaws`](http://hackage.haskell.org/package/quickcheck-classes-0.6.4.0/docs/Test-QuickCheck-Classes.html#v:muvectorLaws).

### CODE REVIEW

**Comment by chessai** [comment]
Thanks!

**Comment by Bodigrim** [comment]
I'd appreciate a release, if possible, please.

**Comment by chessai** [comment]
released as 0.2.5

**Comment by Bodigrim** [comment]
Thanks!

**Pull request merged**
